### ISSUE TITLE
graal / jsonata handles complex parameters incorrectly

### ISSUE THREAD

**Issue by aeberhart** [dashjoin/platform#139]
$echo({"a":[1,2,3]})

yields

{
  "a": {}
}

seems like this issue is caused by the object representation using PolyglotMap which is probably converted to a map by jackson

**Comment by uw4** [comment]
Seems to be an issue with the default type mapping in GraalJS:
https://github.com/oracle/graaljs/issues/214

Fix is expected with GraalVM 22.1 (we're at 22.0.22)

Do we need a workaround until then?
