### ISSUE TITLE
Editor usability consistency

### ISSUE THREAD

**Issue by aeberhart** [dashjoin/platform#157]
There are a couple of things which are inconsistent in the various editors:

* Query Editor: the query is run onChange (focus lost) in the query text field
* JSONata does preview after key-down - need to type space for instance to re-eval expression
* all editors should protect again data loss

**Comment by aeberhart** [comment]
Query Editor: if last keydown is TAB, onChange query eval does not start

**Comment by uw4** [comment]
Moved Monaco into new issue
