### ISSUE TITLE
Allow setting variable values via URL parameters

### ISSUE THREAD

**Issue by aeberhart** [dashjoin/platform#181]
The variable widget allows changing the appearance of pages by storing session values and retrieving them using JSONata: variable.name.

At the moment, the only way to do this is by having the user interact with the widget.

It would be good if values could be encoded in the URL.

Considerations:
* outgoing links on the page: since the value is stored in the browser session, there's no need to append the URL parameter to these links
* data types: URL parameters only support string types. One option would be to use JSON. This would allow to even pass objects like ?par={"x":1}. Note that a simple string would have to be encoded using quotes in this case: ?par="string"
* therefore we will only support string parameters. This might require to do type conversions in JSONata: $number("124")

**Comment by ralfhennig** [comment]
Can you please give an example how to retrieve the URL parameter in Jasonata on a widget on a dashboard page?

**Comment by aeberhart** [comment]
the documentation is here:
https://github.com/dashjoin/platform#variable

this would be an example:
https://demo.my.dashjoin.com/#/page/chart-stacked-bar?year=1998

this is the source for the example:
https://github.com/dashjoin/dashjoin-demo/blob/main/model/page/chart-stacked-bar.json
