### ISSUE TITLE
Navigation pane on left side to be resizeable

### ISSUE THREAD

**Issue by ralfhennig** [dashjoin/platform#196]
Could you make the default window left column (where the navigation to Configuration, Dashboards and the databases resides) to be resizeable? some of my tables and views have long names and so I cannot see it unless I scroll horizontally.

**Comment by aeberhart** [comment]
We can introduce a config option for this. For performance reasons, it would be best to get this value with the initial GET /rest/database/crud/config/widget

**Comment by aeberhart** [comment]
Setting is available here:

![image](https://user-images.githubusercontent.com/61732435/195821819-c9e83275-edf0-49cb-b8e5-3fe7a63563e2.png)

After changing the setting, you need to logout and back in.
The file sidenav-width-px.json can be part of your app.
