### ISSUE TITLE
URL parameter in role default page should not get urlencoded. 

### ISSUE THREAD

**Issue by ralfhennig** [dashjoin/platform#203]
Roles can be given a default page for users in the role. How is it possible to append and URL get parameter like /page/mypage?myparameter=1

Just tried to set the page to [/page/Home?x=1](http://localhost:4200/#/page/Home%3Fx%3D1) but it gets urlencoded.

**Comment by ralfhennig** [comment]
any progress on this bug?

**Comment by aeberhart** [comment]
Fixed in the master branch / will be part of 3.0
