### ISSUE TITLE
Local dj user creation doesnt get recognized

### ISSUE THREAD

**Issue by ralfhennig** [dashjoin/platform#212]
Created an user in the file djusers.properties like username=MD5-Hash of password
After I created the entry in the file and waited > 30 min and also started a incognito browser window. I tried to log on as configured in the djusers.properties file, but this dont work.

**Comment by uw4** [comment]
Following these 2 steps, adding a user works as designed (while the platform is running - no waiting required):

## 1. Add the user's password to `djusers.properties`

Important - hash the password salted with username + realm "Dashjoin":
For user "myuser" and password "mypass", need hash of `myuser:Dashjoin:mypass`

For this example the result is `a3f1c2e80af79503cef46f9e198919d3` (see how to calculate below)

So we need to add this line to `djusers.properties`:
```
myuser=a3f1c2e80af79503cef46f9e198919d3
```

## 2. Add the user's role(s) to `djroles.properties`
To give "myuser" the "authenticated" role, add this line to `djroles.properties`:
```
myuser=authenticated
```
Multiple roles can be added with comma separation

## How to calculate
* Linux/MacOS:
```
echo -n "myuser:Dashjoin:mypass" | md5sum -
```

* Windows:
```
powershell Write-Host -NoNewline "myuser:Dashjoin:mypass" >temp.txt
powershell (Get-FileHash -algorithm md5 temp.txt).Hash.ToLower()
del temp.txt
```
need to store the string in a file temp.txt first (please delete after). Make sure there are no additional spaces and newlines

* Online
For test/dev purposes you can also use an online service like https://emn178.github.io/online-tools/md5.html
Note this might be insecure if the online service stores or re-publishes the entered strings!

**Comment by uw4** [comment]
Details will be added to https://dashjoin.github.io/platform/2.5/installation/
