### ISSUE TITLE
Width of the sidebar is not changeable

### ISSUE THREAD

**Issue by ralfhennig** [dashjoin/platform#237]
How can the width of the sidebar be changed?
Is it possible to make it invisible for certain roles?

**Comment by aeberhart** [comment]
You can change the value here:
http://localhost:4200/#/resource/config/dj-config/sidenav-width-px

Note that you must logout and back in once for it to have an effect

TODOs still:

- [ ] document the missing options here: https://dashjoin.github.io/platform/3.0/administration/#configuration-changes
- [ ] depending on the role of the user, decide whether to hide / show the sidebar (currently depends on window width: sidenavOpen = window.innerWidth > 700)
