### ISSUE TITLE
Provide column names (and other parts of the SQL) as parameter

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#260]
It seems that only the values in a query can be given as parameter and not column names or other parts of the SQL (e.g. complete where clauses)

But e.g. for implementing a kind of bulk change, it would be great if columns or even parts of the sql can be given as parameter.

As an example - i want to give the user the possiblity to change a special field for all (or selective) records in a table:

![image](https://user-images.githubusercontent.com/47058152/209409345-7948fb18-5c10-455b-b747-b575a8d858de.png)

So i want to give him the possibility to choose the field, the new value, and maybe even the ids of the records to change (comma separated) - see in screenshot

The query in the query catalog would look like this:

![image](https://user-images.githubusercontent.com/47058152/209409706-4702945e-ad61-46a1-b421-16da9127a2b6.png)

`UPDATE animal SET ${column}=${newvalue} where fk_client=${clientId} ${condition}`

and as the parameters i would give to the query 
column = "breed"
newvalue = "lama"
condition = "and animalid in (2,3,4)"

which should give the final SQL:
`UPDATE animal SET breed='lama' where fk_client='936DA01F-9ABD-4D9D-80C7-02AF85C822A8' and animalid in (2,3,4)`

If i try to give the column name as condition i get a 

`java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "$1" Position: 19`

at the moment.

E.g.: Jasper reports solved it that way:

`INNER JOIN FILE F ON S.FK_FILE = F.ID
WHERE $P!{IDCOLUMN}=$P{ID}
$P!{CONDITION}`

If the parameter has a ! after the $P it is a replacement within the SQL query, otherwise it is a value.

For this kind of changes it would be good, that there is a possibility to show a confirmation dialog (see issue #258 )

**Comment by aeberhart** [comment]
We currently use prepared statements for parameters. The prepared statement API prevents SQL injection so we're a bit reluctant to opening this up. We see the requirement though...

**Comment by pgrill79** [comment]
Hi Andi,  thanks for the update... is there a way to do a update for multiple rows at once ? Because with the $update function i have to provide the PK of the row to update, correct. But if i want to do a bulk update on the table, it would be good if i can also provide a json for a where clause instead of the PK.

The work around would be to do a loop through all records in a table to execute single updates for each row, but it would be much easier if i can provide a where condition.

**Comment by aeberhart** [comment]
$update only works for a single row, but you can use a normal jsonata loop:

```
[1,2,3,4].$string($)
```

this example applies the $string function to all array elements. So you can do something like this:

```
..your query....$update(db, table, $.id, {key, value})
```
