### ISSUE TITLE
Preview of context should have a scrollbar

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#261]
If the preview of the given expession / context is too big, you only see the first line. The textbox should have a scrollbar:

![image](https://user-images.githubusercontent.com/47058152/209470352-83b33d6f-8df0-4011-80eb-de5c8457a1b6.png)

**Comment by aeberhart** [comment]
fits in the content of "JSONata IDE" but this is certainly an immediate improvement we should do
