### ISSUE TITLE
Mix of EJS and ${expression} does not work in HTML widget

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#262]
If i only use EJS in an HTML widget it works fine:

![image](https://user-images.githubusercontent.com/47058152/209474619-bcde9a4a-51e7-4fa9-af1b-81a46810ba75.png)

The link is correctly built and shown:

![image](https://user-images.githubusercontent.com/47058152/209474383-2d4722a2-ad95-451d-92d3-31815dcf51df.png)

But as soon as i combine it with an expression ${expression} somewhere in the widget, e.g.:

![image](https://user-images.githubusercontent.com/47058152/209474626-364b7be7-c9af-435d-b0fe-3a75a0e2da6a.png)

only the expression is resolved, but not the EJS anymore:

![image](https://user-images.githubusercontent.com/47058152/209474468-1780f168-881f-4ec0-a287-6c979d03d283.png)

Maybe this is also a technical limitation and the user has to decide to use either EJS or the expressions ?

**Comment by aeberhart** [comment]
In expression.ts, we apply either the ${var} or the <%=var%> pattern.
It is ok to keep both ways, but the documentation and error message should be more clear.
Mixing both notations should be discouraged, since the EJS might contain JS string templates
