### ISSUE TITLE
Browser freezes when adding a Text widget and start typing ${

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#347]
If you add a Text Widget and start typing ${ in the Field "Element text", the browser freezes after the typing {

**Comment by aeberhart** [comment]
I cannot reproduce this issue. Tried on master branch and 5.1.25-eace531-b32aff7.
Tested Card widget and typed ${  going on to ${email}

Can you please try again or specify a different test scenario? Also, can you open & check the browser console via (F12) to see if there are any JS errors

**Comment by pgrill79** [comment]
Hi Andi,

With Card widget it works for me as well - it only happens if you use the "Text widget":

![image](https://github.com/dashjoin/platform/assets/47058152/f8813dd0-9a2d-4137-a584-823e1c777e2b)

The Console stays empty - tested with Chrome and Edge - Dashjoin 5.1.25-eace531-b32aff7

**Comment by aeberhart** [comment]
Got it - this was caused by an endless recursion which kept re-evaluation the template
(string contains ${ -> run template (which assumed ${...} would be replaced))
