### ISSUE TITLE
Target URL after in Edit widet after Edit Action or Delete Action

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#349]
If you use the Edit widget and Edit or Delete a record, you are forwarded to the table page. There should be a possibility to stay on the same page and even better to define a target URL. Because in our usecase the user should not get to the Table page

**Comment by aeberhart** [comment]
We'll introduce two new properties for the edit widget (in DJ Studio only):

* editRedirect
* deleteRedirect

they can be set with the following values:

* table: (the default) - go back to the table view
* record: stay on the page
* path to page (e.g. page/Info or northwind/EMPLOYEES/2): navigate to this page

At the moment, it is not possible to go "back" via window.history.back()
