### ISSUE TITLE
"Optional confirmation text" on Edit widget has no effect

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#350]
The property "Optional confirmation text" has no effect on the Edit widget. The record is edited or deleted without the confirmation dialog appearing

**Comment by aeberhart** [comment]
should be adressed along with #349

**Comment by aeberhart** [comment]
The behavior currently is as follows:
* all changes on the config DB are carried out immediately, without "undo" - the rationale for this is that changes to databases and functions are usually made right before the user expects to see a new DB table or run the changes function
* drop table and drop column have a user confirmation
* all other tables have "undoable" mutations
* "bulk delete" from the table view is also "undoable" for all tables

**Comment by aeberhart** [comment]
TODOs

- [ ] remove deleteConfirmation from default templates
- [ ] remove deleteConfirmation from the layout editor
- [ ] keep it in dashjoin studio and switch edit mode to "pessimistic" if it is set
