### ISSUE TITLE
Frontend Functions cannot be used in Invoke Methods

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#353]
If i want to use Frontend Functinons in Invoke method this is not possible - only Backend Functions can be used.
As we have many actions tables, which need a refresh afterwards we have to type the complete function into the (very small) Field for the action in the action table.

**Comment by aeberhart** [comment]
In principle, there are 3 ways to do this:

* inspect the contents of the function - if invoke and invoke expression contains client calls, run on the client
* create a new function browser_call()
* allow apps to define custom function via bindings (like in the try.jsonata.org bindings window)

**Comment by aeberhart** [comment]
There are several reasons against allowing browser functions in "invoke" expressions (options 1 and 2). For instance, invoke expressions implicitly define a REST endpoint where a browser function makes no sense.

Once we fix #354, editing the expressions won't be so cumbersome.

Also, you can still call the backend parts and minimize the expression to something like

```
$navigate($call(...)) or ( $call(); $refresh() )
```

we might still introduce option 3 at a later stage
