### ISSUE TITLE
"Table actions" field in Action table very small

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#354]
Because of the issue https://github.com/dashjoin/platform/issues/353 we need to type in complete function blocks into the Action string field in the Action table - this makes it very hard to write the functions:

![image](https://github.com/dashjoin/platform/assets/47058152/cb13788d-f390-484b-b759-a0d925ac4fe0)

**Comment by aeberhart** [comment]
Should also support basic JSONata functions like
* preview via CTRL enter
* monospace font
* multi-line

**Comment by pgrill79** [comment]
Also the expression field in the on-login is quite small:
![image](https://github.com/dashjoin/platform/assets/47058152/43cb46ed-bb59-4e51-b0bf-9e24de636cec)

**Comment by aeberhart** [comment]
on-login is fix in 5.1.30

**Comment by aeberhart** [comment]
changes:
* monospace small font
* min width: 500px with horizontal scroll

preview is hard to do because every expression will base on "selected" which is hard to simulate
