### ISSUE TITLE
Changes in the SQL editor are lost if you take away and bring back the focus

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#355]
If you use the SQL text editor when writing queryies, all changes are lost if you put the focus in another window (e.g. Notepad to copy something) and bring back the cursor again to the SQL window

**Comment by aeberhart** [comment]
happens on the query page only if the query has parameters. E.g. here:
https://demo.my.dashjoin.com/#/config/dj-query-catalog/orgchart

**Comment by aeberhart** [comment]
we switched from ArrayInput (https://marmelab.com/react-admin/ArrayInput.html) to the custom map input that we already use in the layout editor

this avoids the conversions and keeps the form in sync with reloads
