### ISSUE TITLE
Last visited page should be stored in the context or as variable

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#358]
Would be good if the last accessed page can be accessed as variable or in the context.

Background - we have links to special records from different screens, and want to offer the user to go back to the origin screen (without using the back button of the browser).

This can also be used e.g. for the URL after deleting the record
see: https://github.com/dashjoin/platform/issues/349

**Comment by aeberhart** [comment]
we could add a client side jsonata function that access browser history

**Comment by aeberhart** [comment]
can be done by adding this property to the page widget:

        "onRender": "$setVariable('referrer', href)",

see #361
