### ISSUE TITLE
Link Text, instead of complete Link in Action Tables or Display widgets (or tables)

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#359]
If i use the Action Table or Display widget i can use the href property make this text as hyperlink:

![image](https://github.com/dashjoin/platform/assets/47058152/875a8427-8402-425d-871b-e4f0b3ee7ca0)

But in case you have very long links, you want to show the user an Link Text, so proably this way:

"data": {
    "href" : "http://dashjoin.com",
    "linktext" : "Great Tool"
}

which shows "Great Tool" as link text with the target URL behind

**Comment by aeberhart** [comment]
We have this already. The attribute is called "label"
https://dashjoin.github.io/platform/latest/developer-reference/#display

please re-open if you mean something different
