### ISSUE TITLE
Possibility to use String Function in the DJLabel Field

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#360]
![image](https://github.com/dashjoin/platform/assets/47058152/fe97fe0e-2de8-4203-8bc0-2c190e22611b)

Would be great if you can use String function in this field. The use case is that e.g. we want to remove leading zeros or do other string manipulations to the value of the field

**Comment by aeberhart** [comment]
this is actually not that trivial. The problem are the autocomplete cases. Assume, you have a label that is set to the employee name. When you edit a filter or a foreign key for employee and start to type "smi", a DB query select * from employee where name like "smi*" is run in order to return DB matches with the prefix "smi" (Smith, Smitts, etc...)

Can you provide a couple of examples? There might be a feasible compromise.

**Comment by pgrill79** [comment]
E.g in our usecase we have the origin of an animal (e.g.:) CH and the eartag, which is stored with leading zeros. in the label i havce ${Origin}${Eartag}, but the eartag is stored in the DB with leading zeros, but should be displayed without the leading zeros. (in the meantime this is no issue anymore, as we removed the leading zeros also in the DB.

But another example is e.g. we have in the DB the Farm Name, and Lastname and Firstname of the Contact Person. in the Label i have
${Name}, ${Lastname}${Firstname} . But as the Name can be Empty, sometimes it shows:
", Grill Patrik" - so in that case i would need to remove the , at the beginning and do a trim.

**Comment by aeberhart** [comment]
Unfortunately, this is not really feasible. Consider the noethwind DB and an employee label of 

```
${LAST_NAME}, ${FIRST_NAME}
```

When you start to type "da" in the "reports_to" input field, the platform runs this query:

```
select "EMPLOYEE_ID", concat('', LAST_NAME, ', ', FIRST_NAME, '') from "EMPLOYEES" where concat('', LAST_NAME, ', ', FIRST_NAME, '') ILIKE 'd'
```

There is also a default "brute force" implementation for databases that do not support this kind of query (basically a select all and filter on the backend, not the DB). Any kind of programming logic beyond the template mechanism would have to be mapped to the query language. If this is no longer possible, we would have to fall back to the default implementation, which can be very expensive for large datasets.
