### ISSUE TITLE
Function onLoad which is called at the beginning of each page

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#361]
Would be great if there is a standard function which is called before opening / loading a page.

Similar to on-login when the user logs in. With that method you can also solve e.g. the isse:

https://github.com/dashjoin/platform/issues/358

By just putting the href then into a variable.

**Comment by aeberhart** [comment]
We discussed this in the past already. The problem is that there is not UI element for "page" in the layout editor.
We could make a onLoad JSONata string available via Dashjoin Studio though
