### ISSUE TITLE
Prefilled Input fields in Button widget

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#362]
Because of https://github.com/dashjoin/platform/issues/349 we are limited in using the Edit widget.

So we also could do this with the button widget, but in that case it would be great if we can prefill the Input Fields with the actual values.

**Comment by aeberhart** [comment]
I guess the variable widget does not help here?
It works like Button but pre-fills the form with "variable".
The solution would be to allow specifying a JSONata expression that computes the form value before rendering it. In this case, the following two widgets would do the same thing:

```
widget: Button
init: variable
```

and

```
widget: Variable
```
