### ISSUE TITLE
Link in Action table does not open the page

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#365]
I am on a dashboard page where i have an action table - within the action table i have the following Content_

`[{
    "Name": {
      "label": "automateIT GmbH",
      "href": "http://localhost:19010/#/wooltest/client/e4f0ea02-20cf-497b-ae48-6f28bcb64823?onbehalf=00000000"
    },
    "TVD / Reference": "00000000",
    "Owner": 0,
    "Keeper": 85,
    "Breeder": 0,
    "Address": "Chrüzwies",
    "ZIP / City": "8852 Altendorf",
    "Country": "",
    "Phone": null,
    "Mobile": null,
    "Email": null,
    "URL": {
      "label": "http://www.automateit.ch",
      "href": "http://www.automateit.ch"
    }
  }]`

The URLs Name and URL are displayed correctly:
![image](https://github.com/dashjoin/platform/assets/47058152/8809415a-c9cf-46c5-aebf-de83d0aff0d5)

But if i click on the "automate IT GmbH" Link he somehow tries to changes the page but comes immidiately back to the dashboard page. If i do a right click and say "Open page in new tab" it works and the client is opened. (so the link is correct)

The link "www.automateit.ch" works when i click directly in the table. So maybe related if the target is localhost or the base url is the same as the current page ?

**Comment by aeberhart** [comment]
This is actually expected behaviour, which stems from the hash-based routing strategy (https://reactrouter.com/ja/main/router-components/hash-router)

You have to omit the /# in the URL and use this path:

/wooltest/client/e4f0ea02-20cf-497b-ae48-6f28bcb64823?onbehalf=00000000
