### ISSUE TITLE
Error message when input does not match regex not clear

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#366]
If the text input for an input field does not match the defined regular expression, the error message is a little bit cryptic to the user:

![image](https://github.com/dashjoin/platform/assets/47058152/d8e6ef18-a1b9-4388-b3d9-aa8e27e1927e)

Proposals:

1. Show the expected regex (also not very clear to the user but better than [object Object])
2. Show the input description as error message - then you can describe the user what is expected

**Comment by aeberhart** [comment]
Went for option 1). The message now is:
Must match a specific format (regexp): A+B+C+
Not ideal, but at least this only shows up once the user tries to submit with an illegal value.

Option 2): input and description are already visible via label / tooltip and probably do not offer any additional hint as to what's wrong
