### ISSUE TITLE
"Dynamic" Homepage for users (Expressions in Homepage property)

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#367]
With the properties in the tenant users i can set a homepage for every tenantuser (or role).
But in our case, every user is also a record in the client table, and i want that the homepage of the user is its record page in the database:

E.g.: wooltest.automateit.ch/wooltest/client/<GUID>

So i would need to set a expression in the homepage property field, which gets me the GUID (which is the primary key) for a username, and set this as Homepage property.

**Comment by aeberhart** [comment]
You can already do this by using on-login and setVariable:

This example loads a record from the DB and uses a value in there to set the "homepage" variable:

```
{
    "ID": "on-login",
    "string": "$setVariable(\"homepage\", \"/page/\" & $read(\"sqlite\", \"REQUESTS\", 6).name)"
}
```

**Comment by aeberhart** [comment]
Please close the issue if this solution works for you

**Comment by pgrill79** [comment]
The proposed solution works. Thanks
