### ISSUE TITLE
FK Fields / Values in Edit Widget are only resolved in Edit Mode

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#375]
Our animals have FKs to the table breed and sex. The DJ-labels on the referenced tables are set to ${name}

When i use now the Edit widget, instead of the Names, the IDs are shown:

![image](https://github.com/dashjoin/platform/assets/47058152/b7c6f54e-36cb-4f0a-bb50-37cfc2856ac4)

It was expected that the values are resolved - this only happens when going to the Edit mode:

![image](https://github.com/dashjoin/platform/assets/47058152/e9483520-53d3-4790-a3ab-9846e6138134)

When leaving the edit mode, the values are still resolved until a refresh is done.

When try to edit the values - it is correct that the Names are shown:

![image](https://github.com/dashjoin/platform/assets/47058152/aa571107-d7b5-466f-86f8-97d9e637af87)

![image](https://github.com/dashjoin/platform/assets/47058152/2cc67517-ded6-469c-8906-c0fdc0c016d5)

It also would be good if the input is a non editable Select box - at the moment you can type in Values, even when changing the type to Select:
![image](https://github.com/dashjoin/platform/assets/47058152/5c663926-e204-48cc-a05b-d3807fc91092)

**Comment by aeberhart** [comment]
we improved the foreign key reference fields for the 5.2 release and this should already be fixed

**Comment by pgrill79** [comment]
Yes - i can confirm it is fixed with 5.1.30
