### ISSUE TITLE
Links in tables not resolved correctly (PreRelease 5.1.30)

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#377]
Links in table were not resolved correctly in PreRelease [5.130](studio-dev:5.1.30)

On the left side you see the source running with 5.1.25 on the right side with 5.1.30:

![image](https://github.com/dashjoin/platform/assets/47058152/5d7dc73f-886e-4bd8-83bb-b0073d3dc28d)

Also the link itself look strange and does not work:

http://localhost:19030/#/q_animal_getDescendents/46/0_0

**Comment by aeberhart** [comment]
Can you provide the "descendants" widget config? Is it JSONata or a query?

**Comment by pgrill79** [comment]
It is a query:
![image](https://github.com/dashjoin/platform/assets/47058152/3c1ea650-adcb-4a51-9fc3-3a420856c559)


Maybe as notice: it has two FK, which points to the same table - maybe this causes issues ? (It worked in the release 5.1.25)

This is the query behind:
`SELECT
 "a1"."animalnr" as "Animal Nr", COALESCE("a1"."origin",'') || "a1"."eartag" as "Ear tag", "a1"."id" as "Name", "sex"."name" as "Sex", "a1"."color" as "Color", "a1"."birth" as "Date of birth", CASE WHEN "a1"."deceased" THEN 'Yes' ELSE 'No' END as "Deceased", a2.id AS "Other parent"
FROM
  relationsrecursive r1
    INNER JOIN animal a1 ON root = a1.id
    INNER JOIN relationsrecursive r2 ON r1.root= r2.root
    INNER JOIN animal a2 ON r2.id = a2.id
    LEFT JOIN sex on a1.fk_sex=sex.id
WHERE
  r1.id = ${animalId} AND length(r1.relativerelation) = 1 AND length(r2.relativerelation) = 1 AND r1.relativerelation != r2.relativerelation`

**Comment by aeberhart** [comment]
this was a side effect of supporting tables like 

```
CREATE TABLE something (
  column1, 
  column2, 
  column3, 
  PRIMARY KEY (column1, column2)
)
```

where the first PK column links to  /db/table/key1_key2

the condition was applied too broadly such that it broke in case of this query.
Now, it is only applied to the table widget (select * from table) on the table page
