### ISSUE TITLE
Possibility to use comparators in Action Table

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#379]
It would be great if you can use different operators for filtering in the action table. E.g. if there is a number or a date column, to give the possiblity to filter every thing > or < than the number or date.

**Comment by aeberhart** [comment]
we can maybe re-use the query editor logic

**Comment by aeberhart** [comment]
in table and actionTable widgets, you can prefix the filter with one of the following operators followed by a space:

* <
* <=
* &gt;
* &gt;=
* != or <>

<img width="297" alt="image" src="https://github.com/user-attachments/assets/5152f15b-f0c7-4a7c-91ff-905db534ee11">

This does not work on the table pages, where filters are pushed down to the database. The filters are applied on the UI only
