### ISSUE TITLE
Expression for select options works in "Button" widget, but not in Edit widget

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#381]
I have an edit widget, where i have a FK - i want to display only special options in the select widget - the preview works fine:

![image](https://github.com/dashjoin/platform/assets/47058152/031ae9d2-c9dd-4d6c-b1b7-3420c472fb20)

but if you save, you still see all available options for the FK:
![image](https://github.com/dashjoin/platform/assets/47058152/09cf4b80-f4a5-47c3-8cd0-94b67c6a5852)

It works fine if the Select widget is within a button widget (same expression used)

**Comment by aeberhart** [comment]
in the switch code, moved
if (schema.widget === 'select')
before
if (schema.displayWith === 'fk')
to make sure a custom select has precedence
