### ISSUE TITLE
Action behind Button widget is triggered although input is invalid

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#382]
I have a button widget, with some input "validations".

When the button is clicked, i call a function that does some database actions.

I would expect that if the input is invalid, (because of regex, mandatory, eg), the action is not triggered. But it seems that even if the validation throws errors, the action behind is called nevertheless:

![image](https://github.com/dashjoin/platform/assets/47058152/fb129030-49e2-444c-9772-214c5028d880)

(The db actions should not be triggered)

This is the code behind the button:

`$result:= $call("db_insertAnimal",
{

"ctx":$,
"clientId":$.value.id, 
"origin":$.form.origin, 
"eartag":$.form.eartag, 
"name":$.form.name, 
"fk_breed":$.form.breed, 
"fk_sex":$.form.sex, 
"color":$.form.color, 
"birth":$.form.dateofbirth, 
"deceased":$.form.deceased
}
);`

**Comment by aeberhart** [comment]
That's a known issue in the 5.1.30 release. Will be addressed before 5.2 is released.

Background: The form validation was incompatible with an update of the react core package. Therefore, we needed to temporarily disable the validation blocking submission
